include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: warning
    missing_return: warning
    ## FIXME: https://github.com/rrousselGit/freezed/issues/488#issuecomment-894358980
    invalid_annotation_target: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    require_trailing_commas: true
    sort_constructors_first: true
