name: todo_list
description: A simple ToDo list application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.4
  table_calendar: ^3.0.9
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3

flutter:
  uses-material-design: true
