name: todo_list
description: A simple ToDo list application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  dartx: ^1.2.0
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  omni_datetime_picker: ^1.0.8
  path_provider: ^2.1.1
  riverpod_annotation: ^2.1.5
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  custom_lint: ^0.5.2
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.1
  isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.2
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
